### ISSUE TITLE
gprbuild could not locate gprlib

### ISSUE THREAD

**Issue by Earnestly** [AdaCore/xmlada#1]
* gcc (GCC) 6.1.1 20160501
* GPRBUILD Pro 17.0w (20150615) (x86_64-pc-linux-gnu)

I configured my gprbuild bootstrap with `--libexecdir=/usr/lib` (see https://github.com/AdaCore/gprbuild/issues/2#issuecomment-217747645) but when building xmlada with the following:

```sh
./configure --prefix=/usr --enable-shared
make relocatable
```

I get these errors:

```
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking whether gnat can build shared libs... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
configure: creating ./config.status
config.status: creating shared.gpr
config.status: creating Makefile
config.status: creating tests/dom/default.gpr
gprbuild -j0 -m -p -XLIBRARY_TYPE=relocatable -XBUILD=Production -XPROCESSORS=0 xmlada.gpr
gprbuild: could not locate library builder "/usr/libexec/gprbuild/gprlib"
Makefile:55: recipe for target 'relocatable' failed
```

While the file `/usr/lib/gprbuild/gprlib` does exist, `gprbuild` seems to be looking for it in `/usr/libexec` instead.  I can't seem to find anything in the xmlada repo which relates to this search path, is it something `gprbuild` itself hardwires?

**Comment by t-14** [comment]
> is it something gprbuild itself hardwires

It is recorded in `share/gprconfig/linker.xml`. I'd rather not change this invariant to be perfectly honest. Looking for execs in libexec looks more correct to me.

**Comment by Earnestly** [comment]
`libexec` is a Debianism, not everyone uses it.

**Comment by t-14** [comment]
I understand, but at the moment the build procedure doesn't involve patching the knowledge base, I prefer to keep the macros to a minimum.

**Comment by Earnestly** [comment]
Why offer `./configure --libexecdir=...` for `gprbuild`? :S

**Comment by t-14** [comment]
Indeed. Probably an oversight/copy-paste somewhere.

**Comment by Earnestly** [comment]
Can you explain why `libexec` is invariant btw?  How is this fact used to guarantee anything?

**Comment by t-14** [comment]
The aim is that the build process is simpler and resulting installations are uniform across all platforms that we support. Since for us the biggest focus is on maintenance, additional complexity from installation variations would be shooting ourselves in the foot.

**Comment by Earnestly** [comment]
I don't even.
