### ISSUE TITLE
Releases needed

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/xmlada#12]
Could we please have tags/releases corresponding to CE releases? the last release here is from 2016, and doesn’t compile with CE 2019.
This means that nothing that uses xmlada can be put into an Alire crate.
(Actually, what it means is that any Alire crate must ignore the fact that there’s an xmlada crate and hope that the user’s system has a working xmlada installed)

**Comment by pmderodat** [comment]
Hello Simon,

Crates in Alire don’t necessarily need to get their sources from a git commit: they can use a source archive insted. You can find the source package for XML/Ada’s Community 2019 release here: <https://www.adacore.com/download/more> and you can see how we did similar things for GNATcoll in <https://github.com/alire-project/alire-index/blob/devel-0.1/index/gn/gnatcoll.toml>.

Hovewer, note that there are project file issues between XML/Ada’s and how Alire handles project files. See <https://github.com/alire-project/alire/issues/290> for more information (from my own try to add XML/Ada to Alire). It’s this specific problem that translates into Alire having to assume that XML/Ada is already installed with the toolchain.

**Comment by simonjwright** [comment]
@pmderodat - I see, thanks for the explanation. I still think some tags would be useful! (I’ve just used the latest `master` commit for my macOS FSF builds)

**Comment by pmderodat** [comment]
Sure! :-) Out of curiosity, given that source archives are available, what makes you need tags/branches, in addition?

**Comment by simonjwright** [comment]
The CE archives have had the GCC runtime library exception stripped out.

**Comment by t-14** [comment]
We have tagged commits corresponding to GNAT Community 2018 and GNAT Community 2019.
