### ISSUE TITLE
Version package stuck to 18.0w.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/xmlada#14]
Hello,
Version in configure still refers to 18.0w even for more recent ones:
[PACKAGE_VERSION='18.0w'](https://github.com/AdaCore/xmlada/blob/master/configure#L582)
(many other references exist)
HTH, Pascal.

**Comment by t-14** [comment]
We don't maintain this version number by hand anymore, we patch it on the fly in production depending on the version we are producing. Consider "18.0w" as a magic value, to be replaced by whatever version number is needed.
