### ISSUE TITLE
Unable to store special characters instrings

### ISSUE THREAD

**Issue by bib1963** [AdaCore/xmlada#19]
You cannot store symbols in strings.

I need the degree symbol.

Using Ada.Characters.Latin_1.Degree_Symbol causes the program to crash:
raised UNICODE.CES.INVALID_ENCODING : unicode-ces-utf8.adb:258

If you try and enter the HTML symbol definition, "&#176;", then the ampersand gets quoted out.

**Comment by briot** [comment]
The behavior you describe in the first part is expected. As the name of the Ada package implies, this is a latin-1 encoding (outside of the 1-128 range), so is invalid UTF-8.

And of course Ada knows nothing about HTML encoding when you using Put_Line, so it just outputs the bytes you provided as input, including the ampersand.

So use the proper UTF-8 encoding, see for instance http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=00B0&mode=hex, where the name can be used to find it in the XML/Ada sources:

 unicode.names.latin_1_supplement.Degree_Sign

**Comment by t-14** [comment]
Thank you for stepping in, Manu!

**Comment by bib1963** [comment]
Nope.

I have code:
`procedure Add_Min_Max (Min_Max_Str : String; X_Pos : String; Y_Pos : String) is
      Text_Node : DOM.Core.Element;
      Text      : DOM.Core.Text;
   begin
      Text_Node := DOM.Core.Documents.Create_Element (LDocument, "text");
      DOM.Core.Elements.Set_Attribute (Text_Node, "x", X_Pos);
      DOM.Core.Elements.Set_Attribute (Text_Node, "y", Y_Pos);
      DOM.Core.Elements.Set_Attribute (Text_Node, "class", "def-maroon");
      DOM.Core.Elements.Set_Attribute (Text_Node, "text-anchor", "left");
      Text_Node := DOM.Core.Nodes.Append_Child (Root_Node, Text_Node);
      Text := DOM.Core.Documents.Create_Text_Node (LDocument, Min_Max_Str);
      Text := DOM.Core.Nodes.Append_Child (Text_Node, Text);
   end Add_Min_Max;`

and if I set Min_Max_String to "This is the &#00B0 symbol", then XMLAda convert the string to and displays as "This is the &amp#00B0 symbol".

Nor can you have String := "This is the " & Unicode.Names.Latin_1_Supplement.Degree_Sign & " symbol"; since the unicode symbol is not a string and nor can you convert it.
