### ISSUE TITLE
ld cannot find -lgnat-6.1

### ISSUE THREAD

**Issue by Earnestly** [AdaCore/xmlada#2]
* gcc (GCC) 6.1.1 20160501
* GPRBUILD Pro 17.0w (20150615) (x86_64-pc-linux-gnu)

During linking I get the following errors:
```
gprbuild -j4 -m -p -XLIBRARY_TYPE=relocatable -XBUILD=Production -XPROCESSORS=4 xmlada.gpr
gprlib xmlada_unicode.lexch
gcc -shared -o /home/earnest/build/store/ada-xmlada-git/src/xmlada/unicode/lib/relocatable/libxmlada_unicode.so.17.0w ... @/home/earnest/build/store/ada-xmlada-git/src/xmlada/unicode/obj/relocatable/GNAT-TEMP-000002.TMP
/usr/bin/ld: cannot find -lgnat-6.1
collect2: error: ld returned 1 exit status
gprlib: /usr/bin/gcc execution error
gprbuild: could not build library for project xmlada_unicode
Makefile:55: recipe for target 'relocatable' failed
make: *** [relocatable] Error 4
```

I'm not sure why `xmlada_unicode` is searching for a `libgnat-6.1` when the GCC build of Ada only includes 
`/usr/lib/libgnat-6.so` and `/usr/lib/libgnat.so`.  More importantly, why is to even attempting to use a versioned library in the first place?

Is this caused by the following code in `xmlada_unicode.gpr`?

```ada
for Library_Version use "lib" & Project'Library_Name
  & Shared.So_Ext & "." & Shared.Version;
```

If this is not the case and a symlink for `libgnat-6.1.so` is supposed to exist it may be a packging bug with the distribution and I can report it there instead. (The curious issue here is that it wants `6.1` while gcc is at either `6` or `6.1.1`.)

**Comment by Earnestly** [comment]
Adding a temporary symlink to get around this, I notice as well that the shared librares are using insecure `RPATH`s as well.

```
Insecure RPATH '/home/earnest/build/store/ada-xmlada-git/src/xmlada/unicode/lib/relocatable/' in file 'lib/xmlada/xmlada_input.relocatable/libxmlada_input_sources.so.17.0w'
Insecure RPATH '/usr/lib64' in file ('lib/xmlada/xmlada_unicode.relocatable/libxmlada_unicode.so.17.0w'
Insecure RPATH '/home/earnest/build/store/ada-xmlada-git/src/xmlada/input_sources/lib/relocatable/' in file 'lib/xmlada/xmlada_sax.relocatable/libxmlada_sax.so.17.0w'
Insecure RPATH '/home/earnest/build/store/ada-xmlada-git/src/xmlada/sax/lib/relocatable/' in file 'lib/xmlada/xmlada_dom.relocatable/libxmlada_dom.so.17.0w'
Insecure RPATH '/home/earnest/build/store/ada-xmlada-git/src/xmlada/dom/lib/relocatable/' in file 'lib/xmlada/xmlada_schema.relocatable/libxmlada_schema.so.17.0w'
```

**Comment by briot** [comment]
This seems to be a known issue in gprbuild, reported in https://github.com/AdaCore/gprbuild/issues/5

I'll close this issue in xmlada, and will let the gprbuild people handle that
