### ISSUE TITLE
There's no gpl-2018 branch

### ISSUE THREAD

**Issue by jrmarino** [AdaCore/xmlada#9]
The 2018 products from Adacore seem to be out, but unlike previous years, there's no gpl-2018 branch, nor  is there a tag or release that points to the equivalent of the 2018 GPL release.

What branch and tag represents xmlada GPL-2018?
Perhaps it should be tagged and/or branched to match previous years.

**Comment by t-14** [comment]
We have tagged commits corresponding to GNAT Community 2018 and GNAT Community 2019.
